spring.application.name=HRRecruitmentManagementSystem

spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_xgCSMyxr?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=u_Pfbtjl
spring.datasource.password=t8iOOfKx2vq7

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sudhas333777@gmail.com
spring.mail.password=mykl czbx zhzm yphu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true